name: final-tut
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38hab1e662_1001
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.14.3=py38h0e640b1_1
  - chardet=3.0.4=py38h9bdc248_1008
  - cryptography=3.2.1=py38hd8c33c5_0
  - icc_rt=2019.0.0=h0cc432a_1
  - idna=2.10=pyh9f0ad1d_0
  - intel-openmp=2020.2=254
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38hb782905_0
  - mkl_fft=1.2.0=py38h45dec08_0
  - mkl_random=1.1.1=py38h47e9c7a_0
  - numpy=1.19.2=py38hadc3359_0
  - numpy-base=1.19.2=py38ha3acd2a_0
  - openssl=1.1.1h=he774522_0
  - pandas=1.1.3=py38ha925a31_0
  - pip=20.2.4=py38haa95532_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyopenssl=19.1.0=py_1
  - pysocks=1.7.1=py38h9bdc248_2
  - python=3.8.5=h5fd99cc_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=py_0
  - requests=2.25.0=pyhd3deb0d_0
  - scipy=1.5.2=py38h14eb087_0
  - setuptools=50.3.1=py38haa95532_1
  - six=1.15.0=py38haa95532_0
  - sqlite=3.33.0=h2a8f88b_0
  - update_checker=0.18.0=pyh9f0ad1d_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - websocket-client=0.57.0=py38h32f6830_3
  - wheel=0.35.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py38h32f6830_1
  - wincertstore=0.2=py38_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - praw==7.1.0
    - prawcore==1.5.0
    - urllib3==1.26.2
prefix: G:\Anaconda\envs\final-tut
